# Generated by Django 5.2.8 on 2025-12-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings_service', '0003_fillLocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='images_id',
            field=models.JSONField(default=list),
        ),
    ]
